name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/__lint.yml

  test:
    permissions:
      contents: read
    uses: ./.github/workflows/__test.yml

  build:
    needs: [lint, test]
    permissions:
      contents: read
    uses: ./.github/workflows/__build.yml
    with:
      goos: '["linux"]'
      goarch: '["amd64"]'

  smoke-test:
    needs: build
    permissions:
      contents: read
    uses: ./.github/workflows/__smoke-test.yml
